FROM python:3.9-alpine
RUN apk add --no-cache libgcc zlib-dev jpeg-dev
RUN pip install --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple pillow==9.5.0 bottle==0.12.25
WORKDIR /app
COPY slide.py .
EXPOSE 3001
CMD ["python", "-u", "slide.py"]
