# 基础镜像 
FROM alpine 
 
# 设置工作目录
WORKDIR /app/
 
# 声明代理环境变量（默认值为空）
#ENV HTTP_PROXY=""
#ENV HTTPS_PROXY=""
#ENV NO_PROXY=""
# 新增SOCKS5代理支持 
#ENV SOCKS5_PROXY=""
 
# 暴露应用端口
EXPOSE 16214
 
# 容器启动命令 
ENTRYPOINT ["/app/TVHelper"]
