name: drpys
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Download Python dependencies with platform compatibility
        run: |
          mkdir -p packages
          python -m pip install --upgrade pip
          # 下载兼容manylinux和Alpine的包
          pip download \
            -d packages \
            -r requirements.txt \
            -i https://mirrors.aliyun.com/pypi/simple/ \
            --platform manylinux2014_x86_64 \
            --only-binary=:all: \
            --verbose
          ls -l packages/

      - name: Clean Docker cache
        run: |
          docker system prune -af
          docker builder prune -af

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile-drpys
          push: true
          tags: taoxg/drpys:latest
          platforms: linux/amd64
          no-cache: true
          progress: plain
    
