name: Docker Multi-Arch Build and Push

   on:
     schedule:
       - cron: "0 0 * * *" # 每天 UTC 时间 00:00 运行
     workflow_dispatch:

   jobs:
     check-upstream:
       runs-on: ubuntu-latest
       steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Set up Docker
           uses: docker/setup-buildx-action@v2

         - name: Check upstream image
           run: |
             docker pull dpanel/dpanel:lite --quiet
             ./check-upstream.sh
#  push:
#    branches:
#      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: taoxg/dpanel:lite
          platforms: linux/amd64,linux/arm64
