name: Telegram Channel Monitor

on:
#  schedule:
#    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 获取完整历史记录
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
    
    - name: Run monitor script
      env:
        CHANNEL_NAME: "juejijianghu"
      run: |
        python web_monitor.py
        
    - name: Show directory structure
      run: |
        echo "当前工作目录:"
        pwd
        echo "文件列表:"
        ls -la
        echo "检查目标文件:"
        ls -la *.zip *.txt || echo "No target files found"
    
    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        if git diff --quiet && git diff --staged --quiet; then
          echo "没有变化需要提交"
        else
          git commit -m "Auto-update from Telegram channel"
          git push
        fi
